#!/bin/bash
#
# Update persistent monitors configuration
# This script updates the monitors-persistent.conf file with the current monitors.conf settings.
#

mon_config="${HOME}/.config/hypr/monitors.conf"
pers_config="${HOME}/.config/hypr/monitors-persistent.conf"

marker_section_custom="### Custom monitors configuration (can be edited by user)"
marker_section_persistent="### Persistent/actual monitors configuration (auto-generated, do not edit)"

regex_config_line="^monitor\s*=.*$" # Matches monitor configuration lines

get_monitor_name() {
    echo "$1" | cut -d'=' -f2 | cut -d',' -f1
}

declare -a mon_persistent_lines

declare -a mon_custom_lines
declare -a mon_custom_names

declare -a mon_new_lines
declare -a mon_new_names

if [[ -f "$pers_config" ]]; then
    in_custom_section=false
    while IFS= read -r line; do
        if [[ "$line" == "$marker_section_custom" ]]; then
            in_custom_section=true
        elif [[ "$line" == "$marker_section_persistent" ]]; then
            in_custom_section=false
        elif [[ "$in_custom_section" == true ]]; then
            mon_custom_lines+=("$line")
            if [[ "$line" =~ $regex_config_line ]]; then
                mon_custom_names+=("$(get_monitor_name "$line")")
            fi
        elif [[ "$in_custom_section" == false && "$line" =~ $regex_config_line ]]; then
            mon_persistent_lines+=("$line")
        fi
    done < "$pers_config"
fi
if [[ -f "$mon_config" ]]; then
    while read -r line; do
        if [[ "$line" =~ $regex_config_line ]]; then 
            mon_new_lines+=("$line")
            mon_new_names+=("$(get_monitor_name "$line")")
        fi
    done < "$mon_config"
fi

# Prepare new monitors-persistent.conf
temp_pers_config="$(mktemp)"
{
    echo "# This file is auto-generated by displays-configs-update.bash on $(date +"%D at %T")."
    echo ""

    echo "$marker_section_custom"
    for line in "${mon_custom_lines[@]}"; do
        echo "$line"
    done

    echo "$marker_section_persistent"
    echo "# Monitors in the current configuration (monitors.conf)"
    for line in "${mon_new_lines[@]}"; do
        name=$(get_monitor_name "$line")
        # If the monitor is in the custom list, skip it
        if [[ " ${mon_custom_names[*]} " == *" $name "* ]]; then continue; fi
        echo "$line"
    done
    echo "# Persistent monitors from previous configurations"
    for line in "${mon_persistent_lines[@]}"; do
        name=$(get_monitor_name "$line")
        # If the monitor is in the custom or new list, skip it
        if [[ " ${mon_custom_names[*]} " == *" $name "* ]]; then continue; fi
        if [[ " ${mon_new_names[*]} " == *" $name "* ]]; then continue; fi
        echo "$line"
    done
} > "$temp_pers_config"

mv "$temp_pers_config" "$pers_config"
rm -f "$temp_pers_config"
