// General
scale=1.3
spacing=5
fontFamily="Monospace"

// Background
backgroundImageEnable=true
backgroundColor="#000000"

// LoginPanel
fieldHeight=25
fieldWidth=125
placeholder_text="user: "

// PowerModesPanel
buttonSize=25

// Clock
clockFontSize=35
dateFontSize=15
